// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface BlogPost {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  seo_description?: string;
  target_etf?: string;
  tickers?: string;
  sentiment?: string;
  signal_score?: number;
  signal_label?: string;
  source_news_url?: string;
  auto_generated?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface NewsItem {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  source?: string;
  source_url?: string;
  raw_content?: string;
  published_external_at?: string;
  analyzed?: boolean;
  target_etf?: string;
  tickers?: string;
  sentiment?: string;
  score?: number;
  importance?: string;
  reason?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Signal {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  ticker: string;
  signal_label?: string;
  score?: number;
  sentiment_score?: number;
  frequency_score?: number;
  momentum_score?: number;
  volatility_score?: number;
  summary?: string;
  generated_at?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface YoutubeVideo {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  video_id: string;
  channel?: string;
  thumbnail?: string;
  description?: string;
  view_count?: number;
  published_external_at?: string;
  summary?: string;
  sentiment?: string;
  relevance?: number;
  score?: number;
  related_ticker?: string;
  keywords?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    blog_posts: BlogPost;
    news_items: NewsItem;
    pages: Page;
    posts: Post;
    signals: Signal;
    youtube_videos: YoutubeVideo;
  }
}